spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://ocassio.asuscomm.com:8080/party-sound?user=nc2018&password=aajz6IXwo5OPd9pczQVuZ0qP}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

