spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${JDBC_DATABASE_URL1:jdbc:postgresql://localhost:5432/party-sound?user=postgres&password=123456}
    initialization-mode: always
    continue-on-error: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

